name: Prod Terraform

on:
push:
branches:
- main
paths:
- 'prod/**'
- 'modules/**'

jobs:
terraform:
runs-on: ubuntu-latest

```
defaults:
  run:
    working-directory: prod

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Terraform Init
    run: terraform init -reconfigure

  - name: Terraform Plan
    run: terraform plan
```
